config/routes.rb
Rails.application.routes.draw do

  get    "sign_up"   => "users#new"
  get    "login"   => "sessions#new"
  post   "login"   => "sessions#create"
  get "logout"  => "sessions#destroy"
  root 'statics#home'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, length: {minimum: 3, maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 55 },
            format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  class << self
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to @user
    else
      render "new"
    end
  end

  def show
    @user = User.find params[:id]
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit :id, :name, :email, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
   def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqueryJasmineRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container body">
  <%= yield %>
</div>

</body>
</html>

app/views/statics/home.html.erb
<div class="jumbotron">
  <h1 class="title">This Is Home Page</h1>
  <p>Welcome <%= logged_in? ? current_user.name : "new guest" %></p>

  <center>
    <% if logged_in? %>
      <%= link_to "Sign Out", logout_path, class: "btn btn-primary btn-lg" %>
    <% else %>
      <%= link_to "Sign Up", sign_up_path, class: "btn btn-primary btn-lg" %>
      <%= link_to "Sign In", login_path, class: "btn btn-primary btn-lg" %>
    <% end %>
  </center>
</div>

app/views/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
</tr>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-6 col-md-offset-3 well">
      <legend>All Users</legend>
      <table width="100%">
        <caption>table title and/or explanatory text</caption>
        <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-4 col-md-offset-4 well">
      <legend>Sign Up</legend>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name%><br />
          <%= f.text_field :name, autofocus: true, class: "form-control" %>
          <span class="error"></span>
        </div>

        <div class="form-group">
          <%= f.label :email%><br />
          <%= f.email_field :email, class: "form-control" %>
          <span class="error"></span>
        </div>

        <div class="form-group">
          <%= f.label :password %><br />
          <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
          <span class="error"></span>
        </div>

        <div class="form-group">
          <%= f.label :confirm_password %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
          <span class="error"></span>
        </div>

        <div class="actions">
          <%= f.submit "Sign Up", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="col-md-4 col-md-offset-4 well">
      <h3> Name: <%= @user.name %></h3>
      <h4> email: <%= @user.email %></h4>
    </div>
  </div>
</div>